In [ ]:
a = 4
b = 5
c = a + b
print(c)

9


In [ ]:
def evenodd():
  n = int(input('Enter a number: '))
  if n % 2 == 0:
    return 'even number'
  else:
    return 'odd number'
print(evenodd())

Enter a number: 5
odd number


In [ ]:
num = [2,24,4]
sum = 0
for i in num:
  sum = sum + i
print(sum)





30


In [ ]:
lst = [4,5,1,2,6,8,7]
min_lst = min(lst)
max_lst = max(lst)
print(max_lst)
print(min_lst)


8
1


In [ ]:
num = [25,25,6,6,5,5]
print(list(set(num)))

[25, 5, 6]


In [ ]:
num = [25,25,6,6,5,5]
unique_num = []
for i in num:
  if i not in unique_num:
    unique_num.append(i)
print(unique_num)

[25, 6, 5]


In [ ]:
def rev():
  lst = [4,5,6]
  lst.reverse()
  return lst
print(rev())

[6, 5, 4]


In [ ]:
lst = [4,5,6]
rev_lst = lst[:: -1]
print(rev_lst)

[6, 5, 4]


In [ ]:
#  Create a tuple and access its elements.
tup = (2,3,4,5,6)
print(tup[0])
print(tup[2])
print(tup[3])

2
4
5


In [ ]:
import numpy as np
a = [9,5,3,1]
print(np.array(a))

[9 5 3 1]


In [ ]:
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [ ]:
a = np.array([[2,3,4], [4,5,6], [6,4,6]])
print(a)
print(a[0,1])

[[2 3 4]
 [4 5 6]
 [6 4 6]]
3


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.add(a,b)
print(c)

[5 7 9]


In [ ]:
#Write a program to merge two dictionaries
dict1 = {'name': 'sumit', 'couse': 'bca'}
dict2 = {'last_name': 'Gupta', 'goal': 'ai engineer'}
dict1.update(dict2)
print(dict1)

{'name': 'sumit', 'couse': 'bca', 'last_name': 'Gupta', 'goal': 'ai engineer'}


In [ ]:
# Write a function to count the frequency of elements in a list
def count(lst):
  freq = {}


In [ ]:
lst = ['apple', 'apple', 'banna', 'banna', 'sav']
freq = {}
for i in lst:
  if i in freq:
    freq[i] +=1
  else:
    freq[i] = 1
print(freq)

{'apple': 2, 'banna': 2, 'sav': 1}


In [ ]:
from collections import Counter
lst = ['apple', 'ab','vc']
freq = Counter(lst)
print(freq)

Counter({'apple': 1, 'ab': 1, 'vc': 1})


In [ ]:
square = {x: x**2 for x in range(1,11)}
print(square)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
lst = [2,1,3,4,3,1,2]
lst.sort()
print(lst)

[1, 1, 2, 2, 3, 3, 4]


In [ ]:
dict1 = {'Pen': 'kalam', 'apple': 3}
key_to_check = 'apple'
if i in key_to_check:
  print(f'key {key_to_check} exite dict')
else:
  print(f"Key '{key_to_check}' does not exist.")


key apple exite dict


In [ ]:
fruit = {'apple', 'banana', 'mangoes', 'pineapple'}
num = set([2,3,5,7])
a = fruit.union(num)
print(a)

{2, 3, 5, 7, 'banana', 'apple', 'mangoes', 'pineapple'}


In [ ]:
def find_common_list(list1, list2):
  common = set(list1) & set(list2)
  return  list(common)
a = [1,2,2,3,6,4]
b = [1,2,3,4,5,6]
print(find_common_list(a,b))

[1, 2, 3, 4, 6]


In [ ]:
def factorial(n):
  result = 1
  if n < 0:
    return 1
  for i in range(1, n+1):
    result *= i
  return result
n = int(input('Enter a factorial number: '))
print(factorial(n))

Enter a factorial number: 5
120


In [ ]:
def factorial(n):
  fact = 1
  for i in range(1, n+1):
    fact *=i
  return fact

print(factorial(5))



120


In [ ]:
a = 'madam'
b = a[:: -1]
check = b==a
print(check)

True


In [ ]:
def polidrome(text):
  return text == text[::-1]
print(polidrome('madam'))

False


In [ ]:
name = 'madan'
check_poli = name[::-1]
if check_poli == name:
  print('its polidrome')
else:
  print('not polidrome')

not polidrome


In [ ]:
name = 'sumit gupta'
count = 0
vowel = 'aeiou'
for i in name:
   if i in vowel:
    count +=1
print(count)

4


In [ ]:
def vowe_count(text):
  count = 0
  vowel = 'aeiou'
  for i in text:
    if i in vowel:
      count +=1
  return count
text = input('enter text: ')
print(vowe_count(text))


enter text: sumti
2
